version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: sovereign-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
        - default

  redis-insight:
    image: redis/redisinsight:latest
    container_name: sovereign-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
    networks:
        - default

volumes:
  redis-data:

