version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: sovereign-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"] # Enables persistence

volumes:
  redis-data:

