version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: sovereign-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"] # Enables persistence

  postgres:
    image: postgres:16
    container_name: sovereign-postgres
    environment:
      POSTGRES_DB: sovereign
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:

