// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Building struct {
	ID                     int32
	PortID                 int32
	Type                   string
	Level                  int32
	CreatedAt              pgtype.Timestamptz
	UnderConstruction      bool
	ConstructionCompleteAt pgtype.Timestamptz
	LastProductionAt       pgtype.Timestamptz
}

type BuildingProduction struct {
	ID             int32
	BuildingTypeID int32
	Level          int32
	ResourceType   string
	ProductionRate int32
}

type BuildingType struct {
	ID            int32
	TypeName      string
	DisplayName   string
	Description   pgtype.Text
	Category      string
	MaxLevel      int32
	BaseCostWood  int32
	BaseCostIron  int32
	BaseCostGold  int32
	BaseBuildTime int32
	CreatedAt     pgtype.Timestamptz
}

type Faction struct {
	ID   int32
	Name string
}

type Player struct {
	ID          int32
	Email       string
	DisplayName string
	Faction     int32
	CreatedAt   pgtype.Timestamptz
	UserID      pgtype.Int4
}

type Port struct {
	ID                           int32
	PlayerID                     int32
	Name                         string
	X                            int32
	Y                            int32
	CreatedAt                    pgtype.Timestamptz
	IslandType                   pgtype.Text
	StartingResourcesInitialized pgtype.Bool
}

type Resource struct {
	PortID    int32
	Wood      int32
	Iron      int32
	Rum       int32
	Sugar     int32
	Tobacco   int32
	Cotton    int32
	Coffee    int32
	Grain     int32
	Gold      int32
	Silver    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID                         int32
	Email                      string
	PasswordHash               string
	EmailVerified              bool
	EmailVerificationToken     pgtype.Text
	EmailVerificationExpiresAt pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}
