// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Building struct {
	ID        int32
	PortID    int32
	Type      string
	Level     int32
	CreatedAt pgtype.Timestamptz
}

type Faction struct {
	ID   int32
	Name string
}

type Player struct {
	ID          int32
	Email       string
	DisplayName string
	Faction     int32
	CreatedAt   pgtype.Timestamptz
}

type Port struct {
	ID        int32
	PlayerID  int32
	Name      string
	X         int32
	Y         int32
	CreatedAt pgtype.Timestamptz
}
