// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: players.sql

package db

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (email, display_name, faction)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, faction, created_at, user_id
`

type CreatePlayerParams struct {
	Email       string
	DisplayName string
	Faction     int32
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.Email, arg.DisplayName, arg.Faction)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Faction,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, email, display_name, faction, created_at, user_id FROM players WHERE email = $1
`

func (q *Queries) GetPlayerByEmail(ctx context.Context, email string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Faction,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, email, display_name, faction, created_at, user_id FROM players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Faction,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
