// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ports.sql

package db

import (
	"context"
)

const createPort = `-- name: CreatePort :one
INSERT INTO ports (player_id, name, x, y)
VALUES ($1, $2, $3, $4)
RETURNING id, player_id, name, x, y, created_at
`

type CreatePortParams struct {
	PlayerID int32
	Name     string
	X        int32
	Y        int32
}

func (q *Queries) CreatePort(ctx context.Context, arg CreatePortParams) (Port, error) {
	row := q.db.QueryRow(ctx, createPort,
		arg.PlayerID,
		arg.Name,
		arg.X,
		arg.Y,
	)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Name,
		&i.X,
		&i.Y,
		&i.CreatedAt,
	)
	return i, err
}

const getPortById = `-- name: GetPortById :one
SELECT id, player_id, name, x, y, created_at FROM ports WHERE id = $1
`

func (q *Queries) GetPortById(ctx context.Context, id int32) (Port, error) {
	row := q.db.QueryRow(ctx, getPortById, id)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Name,
		&i.X,
		&i.Y,
		&i.CreatedAt,
	)
	return i, err
}
